
/* ============================================================
   CRIAÇÃO DO BANCO
============================================================ */

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TechLeiloes')
BEGIN
    CREATE DATABASE TechLeiloes;
END
GO

USE TechLeiloes;
GO

/* ============================================================
   TABELA CATEGORIA
============================================================ */

CREATE TABLE CATEGORIA (
    CATEGORIAID INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAOCATEGORIA VARCHAR(150) NOT NULL,
    DATACRIACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATAATUALIZACAO DATETIME NULL
);



CREATE INDEX IX_CATEGORIA_DESCRICAO ON CATEGORIA(DESCRICAOCATEGORIA);

/* ============================================================
   TABELA CIDADE
============================================================ */

CREATE TABLE CIDADE (
    CIDADEID INT IDENTITY(1,1) PRIMARY KEY,
    NOMECIDADE VARCHAR(150) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

CREATE INDEX IX_CIDADE_NOME ON CIDADE(NOMECIDADE);

/* ============================================================
   TABELA LEILOEIRO
============================================================ */

CREATE TABLE LEILOEIRO (
    LEILOEIROID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE,
    TELEFONE VARCHAR(20),
    WEBSITE VARCHAR(200),
    CADASTROJUNTACOMERCIAL VARCHAR(200)
);

/* ============================================================
   TABELA STATUS
============================================================ */

CREATE TABLE STATUSLEILAO (
    STATUSID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

/* ============================================================
   TABELA USUARIO
============================================================ */

CREATE TABLE USUARIO (
    USUARIOID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    TELEFONE VARCHAR(20),
    DATANASCIMENTO DATETIME NOT NULL,
    PROFISSAO VARCHAR(100),
    DATACRIACAO DATETIME NOT NULL DEFAULT GETDATE()
   
);

/* ============================================================
   TABELA COR
============================================================ */

CREATE TABLE COR(
    CORID INT IDENTITY(1,1) PRIMARY KEY,
    CORCATEGORIA VARCHAR(10),
    CORCATEGORIACONTRASTE VARCHAR(10),
    CATEGORIAID INT NOT NULL,
       
    CONSTRAINT FK_COR_CATEGORIA
        FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIA(CATEGORIAID)
);
/* ============================================================
   TABELA LEILAO
============================================================ */

CREATE TABLE LEILAO (
    LEILAOID INT IDENTITY(1,1) PRIMARY KEY,
    LEILOEIROID INT NOT NULL,
    EDITAL VARCHAR(500),
    DATAPRIMEIRAPRACA DATETIME,
    DATASEGUNDAPRACA DATETIME,
    DESCONTO DECIMAL(5,2),
    MODALIDADE VARCHAR(50) NOT NULL,
    DATAINCLUSAO DATETIME NOT NULL,
    DATACRIACAO DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_LEILAO_LEILOEIRO 
        FOREIGN KEY (LEILOEIROID) REFERENCES LEILOEIRO(LEILOEIROID),

    CONSTRAINT CK_LEILAO_DESCONTO 
        CHECK (DESCONTO >= 0 AND DESCONTO <= 100)
);

CREATE INDEX IX_LEILAO_LEILOEIRO ON LEILAO(LEILOEIROID);

/* ============================================================
   TABELA LOTE
============================================================ */
CREATE TABLE LOTE(
   LOTEID INT NOT NULL IDENTITY(1,1),
   NOMELOTE VARCHAR(100) NOT NULL,
   LOTEPAIID INT NULL,
   PRECOPRIMEIRAPRACA DECIMAL(20,2),
   PRECOSEGUNDAPRACA DECIMAL(20,2),
   VALORAVALIACAO DECIMAL(20,2),
   CONSTRAINT PKLOTE PRIMARY KEY(LOTEID),
   CONSTRAINT FK_LOTE_LOTE FOREIGN KEY (LOTEPAIID) REFERENCES LOTE(LOTEID)
);

/* ============================================================
   TABELA IMOVEL
============================================================ */

CREATE TABLE IMOVEL (
    IMOVELID INT IDENTITY(1,1) PRIMARY KEY,
    CIDADEID INT NOT NULL,
    CATEGORIAID INT NOT NULL,
    LEILAOID INT NOT NULL,
    LOTEID INT NOT NULL,
    SITUACAO VARCHAR(500) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    CEP CHAR(9) NOT NULL,
    DESCRICAO VARCHAR(MAX)NOT NULL,
    AREATOTAL DECIMAL(10,2),
    MATRICULA VARCHAR(100),

    CONSTRAINT FK_IMOVEL_LEILAO
        FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID),
    CONSTRAINT FK_IMOVEL_CIDADE 
        FOREIGN KEY (CIDADEID) REFERENCES CIDADE(CIDADEID),
    CONSTRAINT FK_IMOVEL_CATEGORIA
        FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIA(CATEGORIAID),
   CONSTRAINT FK_IMOVEL_LOTE
         FOREIGN KEY (LOTEID) REFERENCES LOTE(LOTEID)
);
CREATE INDEX IX_IMOVEL_CIDADE ON IMOVEL(CIDADEID);
CREATE INDEX IX_IMOVEL_CATEGORIA ON IMOVEL(CATEGORIAID);
CREATE INDEX IX_IMOVEL_LEILAO ON IMOVEL(LEILAOID);
CREATE INDEX IX_IMOVEL_LOTE ON IMOVEL(LOTEID);


/* ============================================================
   TABELA HISTORICO
============================================================ */

CREATE TABLE HISTORICO (
    HISTORICOID INT IDENTITY(1,1) PRIMARY KEY,
    LEILAOID INT NOT NULL,
    STATUSID INT NOT NULL,
    DATAHISTORICO DATETIME NOT NULL DEFAULT GETDATE(),
    SUCESSO BIT,
    TOTALLEILOES INT,

    CONSTRAINT FK_STATUS_LEILAO
        FOREIGN KEY (STATUSID) REFERENCES STATUSLEILAO (STATUSID),
    CONSTRAINT FK_HISTORICO_LEILAO 
        FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID)
);

CREATE INDEX IX_HISTORICO_LEILAO ON HISTORICO(LEILAOID);

/* ============================================================
   TABELA SINCRONIZACAO
============================================================ */

CREATE TABLE SINCRONIZACAO (
    SINCRONIZACAOID INT IDENTITY(1,1) PRIMARY KEY,
    LEILOEIROID INT NOT NULL,
    DATAINICIOATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATATERMINOATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATAATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE(),
    SUCESSO BIT,

     CONSTRAINT FK_SINCRONIZACAO_LEILOEIRO
        FOREIGN KEY (LEILOEIROID) REFERENCES LEILOEIRO(LEILOEIROID)

);

/* ============================================================
   TABELA PROCESSO
============================================================ */
CREATE TABLE PROCESSO(
   PROCESSOID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   NUMEROPROCESSO VARCHAR(50) NOT NULL,
   LEILAOID INT NOT NULL,

   CONSTRAINT FK_PROCESSO_LEILAO
      FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID)
   );
/* ============================================================
   TABELA FOTO
============================================================ */

CREATE TABLE FOTO (
    FOTOID INT IDENTITY(1,1) PRIMARY KEY,
    IMOVELID INT NOT NULL,
    CAMINHOIMAGEM VARCHAR(300) NOT NULL,

    CONSTRAINT FK_FOTO_IMOVEL 
        FOREIGN KEY (IMOVELID) REFERENCES IMOVEL(IMOVELID)
);

CREATE INDEX IX_FOTO_IMOVEL ON FOTO(IMOVELID);

/* ============================================================
   TABELA FAVORITOS
============================================================ */

CREATE TABLE FAVORITOS (
    FAVORITOSID INT IDENTITY(1,1) PRIMARY KEY,
    LEILAOID INT NOT NULL,
    USUARIOID INT NOT NULL,
    DATAFAVORITO DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_FAVORITOS_USUARIO 
        FOREIGN KEY (USUARIOID) REFERENCES USUARIO(USUARIOID),

    CONSTRAINT FK_FAVORITOS_LEILAO 
        FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID),

    CONSTRAINT UQ_FAVORITO UNIQUE (USUARIOID, LEILAOID)
);

CREATE INDEX IX_FAVORITOS_USUARIO ON FAVORITOS(USUARIOID);



/* ============================================================
   TABELAS DE CONTROLE
============================================================ */

CREATE TABLE NOVOSLEILOES (
   ID INT IDENTITY(1,1) PRIMARY KEY,
    LEILAOID INT,
    SINCRONIZACAOID INT,
    DATAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
   
   CONSTRAINT FK_NOVOSLEILOES_LEILAO
      FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID),
   
   CONSTRAINT FK_NOVOSLEILOES_SINCRONIZACAO
      FOREIGN KEY (SINCRONIZACAOID) REFERENCES SINCRONIZACAO(SINCRONIZACAOID)
);

CREATE TABLE LEILOESREMOVIDOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LEILAOID INT,
    SINCRONIZACAOID INT,
    DATAREGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
   
   CONSTRAINT FK_LEILOESREMOVIDOS_LEILAO
      FOREIGN KEY (LEILAOID) REFERENCES LEILAO(LEILAOID),
   
   CONSTRAINT FK_LEILOESREMOVIDOS_SINCRONIZACAO
      FOREIGN KEY (SINCRONIZACAOID) REFERENCES SINCRONIZACAO(SINCRONIZACAOID)
);


-- comandos git -- 
-- git status
-- git add .
-- git commit -m 'Criação da Service e Models#
-- >> Inclui interfaces vazias para serviços de Imóvel, Leilão, Leiloeiro e Usuário. Cria a classe ResultadoExecucao<T> para padronizar retornos. Adiciona dependências Dapper e SqlClient ao projeto.
-- git config --global user.email "laura_chiarello@live.com"
-- git config --global user.name "Laura Chiarello"
-- git status
-- git log
--> git push origin master
